const TIMEZONES = [
  { label: 'UTC-12:00 - Baker Island', offset: -12, name: 'Etc/GMT+12' },
  { label: 'UTC-11:00 - American Samoa', offset: -11, name: 'Pacific/Pago_Pago' },
  { label: 'UTC-10:00 - Hawaii', offset: -10, name: 'Pacific/Honolulu' },
  { label: 'UTC-09:00 - Alaska', offset: -9, name: 'America/Anchorage' },
  { label: 'UTC-08:00 - Pacific (US & Canada)', offset: -8, name: 'America/Los_Angeles' },
  { label: 'UTC-07:00 - Mountain (US & Canada)', offset: -7, name: 'America/Denver' },
  { label: 'UTC-06:00 - Central (US & Canada)', offset: -6, name: 'America/Chicago' },
  { label: 'UTC-05:00 - Eastern (US & Canada)', offset: -5, name: 'America/New_York' },
  { label: 'UTC-04:00 - Atlantic (Canada)', offset: -4, name: 'America/Halifax' },
  { label: 'UTC-03:00 - Buenos Aires', offset: -3, name: 'America/Argentina/Buenos_Aires' },
  { label: 'UTC-02:00 - South Georgia', offset: -2, name: 'Atlantic/South_Georgia' },
  { label: 'UTC-01:00 - Azores', offset: -1, name: 'Atlantic/Azores' },
  { label: 'UTC±00:00 - London, Lisbon', offset: 0, name: 'Europe/London' },
  { label: 'UTC+01:00 - Berlin, Paris, Rome', offset: 1, name: 'Europe/Berlin' },
  { label: 'UTC+02:00 - Athens, Cape Town', offset: 2, name: 'Europe/Athens' },
  { label: 'UTC+03:00 - Moscow, Nairobi', offset: 3, name: 'Europe/Moscow' },
  { label: 'UTC+04:00 - Dubai', offset: 4, name: 'Asia/Dubai' },
  { label: 'UTC+05:00 - Karachi', offset: 5, name: 'Asia/Karachi' },
  { label: 'UTC+05:30 - India Standard Time', offset: 5.5, name: 'Asia/Kolkata' },
  { label: 'UTC+06:00 - Dhaka', offset: 6, name: 'Asia/Dhaka' },
  { label: 'UTC+07:00 - Bangkok, Jakarta', offset: 7, name: 'Asia/Bangkok' },
  { label: 'UTC+08:00 - Singapore, Beijing', offset: 8, name: 'Asia/Singapore' },
  { label: 'UTC+09:00 - Tokyo, Seoul', offset: 9, name: 'Asia/Tokyo' },
  { label: 'UTC+10:00 - Sydney', offset: 10, name: 'Australia/Sydney' },
  { label: 'UTC+11:00 - Solomon Islands', offset: 11, name: 'Pacific/Guadalcanal' },
  { label: 'UTC+12:00 - Fiji, Auckland', offset: 12, name: 'Pacific/Auckland' },
  { label: 'UTC+13:00 - Tonga', offset: 13, name: 'Pacific/Tongatapu' },
  { label: 'UTC+14:00 - Kiritimati', offset: 14, name: 'Pacific/Kiritimati' },
];

export default TIMEZONES;
